### ISSUE TITLE
It doesn't works on Seagate Personal Cloud

### ISSUE THREAD

**Issue by josivan** [Djailla/nas-os-gateone#1]
Hello, I'm trying to use it on Seagate Personal Cloud, but I always have the error:

**PTY allocation request failed on channel 1**

No more details are available.

How can I solve it?

Thanks

**Comment by Djailla** [comment]
Hello,

Can you be more specific on what you try to achieve ? GateOne allows you to connect to a remote SSH server using the Personal Cloud web interface. Where are you trying to connect ?

**Comment by josivan** [comment]
Hello

My intention was to connect in my personal cloud (using ssh). Only now I have noticed that the main idea of app is to connect in a server different of personal cloud. I was trying to connect in my SPC. It was my confusion. Sorry for that.

**Comment by Djailla** [comment]
@josivan just to be curious, what action / task would you run on the SPC using the SSH access ?

**Comment by josivan** [comment]
I would like to move file between user using root, for example. Or delete file directly from console. Things like that.
